version: '3.7'

services: 
    webserver:
        image: rootlessnginx
        container_name: rootlessnginx
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 0.0.0.0:3000:3000
