version: '3.7'

services:
    webserver:
        image: unprivilegednginx
        container_name: unprivilegednginx
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 0.0.0.0:3000:3000
