version: '3.7'

services:
    webserver:
        image: unprivilegednode
        container_name: unprivilegednode
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 0.0.0.0:3000:3000
