version: '3.7'

services: 
    webserver:
        image: rootlessnode
        container_name: rootlessnode
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 0.0.0.0:3000:3000
