version: '3.7'

services:
    webserver:
        image: unprivilegedaspnetcore
        container_name: unprivilegedaspnetcore
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 0.0.0.0:3000:3000
